# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: meshtastic/channel.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'meshtastic/channel.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18meshtastic/channel.proto\x12\nmeshtastic\"\x83\x02\n\x0f\x43hannelSettings\x12#\n\x0b\x63hannel_num\x18\x01 \x01(\rB\x02\x18\x01R\nchannelNum\x12\x10\n\x03psk\x18\x02 \x01(\x0cR\x03psk\x12\x12\n\x04name\x18\x03 \x01(\tR\x04name\x12\x0e\n\x02id\x18\x04 \x01(\x07R\x02id\x12%\n\x0euplink_enabled\x18\x05 \x01(\x08R\ruplinkEnabled\x12)\n\x10\x64ownlink_enabled\x18\x06 \x01(\x08R\x0f\x64ownlinkEnabled\x12\x43\n\x0fmodule_settings\x18\x07 \x01(\x0b\x32\x1a.meshtastic.ModuleSettingsR\x0emoduleSettings\"Z\n\x0eModuleSettings\x12-\n\x12position_precision\x18\x01 \x01(\rR\x11positionPrecision\x12\x19\n\x08is_muted\x18\x02 \x01(\x08R\x07isMuted\"\xb8\x01\n\x07\x43hannel\x12\x14\n\x05index\x18\x01 \x01(\x05R\x05index\x12\x37\n\x08settings\x18\x02 \x01(\x0b\x32\x1b.meshtastic.ChannelSettingsR\x08settings\x12,\n\x04role\x18\x03 \x01(\x0e\x32\x18.meshtastic.Channel.RoleR\x04role\"0\n\x04Role\x12\x0c\n\x08\x44ISABLED\x10\x00\x12\x0b\n\x07PRIMARY\x10\x01\x12\r\n\tSECONDARY\x10\x02\x42\x63\n\x14org.meshtastic.protoB\rChannelProtosZ\"github.com/meshtastic/go/generated\xaa\x02\x14Meshtastic.Protobufs\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meshtastic.channel_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024org.meshtastic.protoB\rChannelProtosZ\"github.com/meshtastic/go/generated\252\002\024Meshtastic.Protobufs\272\002\000'
  _globals['_CHANNELSETTINGS'].fields_by_name['channel_num']._loaded_options = None
  _globals['_CHANNELSETTINGS'].fields_by_name['channel_num']._serialized_options = b'\030\001'
  _globals['_CHANNELSETTINGS']._serialized_start=41
  _globals['_CHANNELSETTINGS']._serialized_end=300
  _globals['_MODULESETTINGS']._serialized_start=302
  _globals['_MODULESETTINGS']._serialized_end=392
  _globals['_CHANNEL']._serialized_start=395
  _globals['_CHANNEL']._serialized_end=579
  _globals['_CHANNEL_ROLE']._serialized_start=531
  _globals['_CHANNEL_ROLE']._serialized_end=579
# @@protoc_insertion_point(module_scope)
