# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: meshtastic/connection_status.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'meshtastic/connection_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"meshtastic/connection_status.proto\x12\nmeshtastic\"\xd4\x02\n\x16\x44\x65viceConnectionStatus\x12\x39\n\x04wifi\x18\x01 \x01(\x0b\x32 .meshtastic.WifiConnectionStatusH\x00R\x04wifi\x88\x01\x01\x12\x45\n\x08\x65thernet\x18\x02 \x01(\x0b\x32$.meshtastic.EthernetConnectionStatusH\x01R\x08\x65thernet\x88\x01\x01\x12H\n\tbluetooth\x18\x03 \x01(\x0b\x32%.meshtastic.BluetoothConnectionStatusH\x02R\tbluetooth\x88\x01\x01\x12?\n\x06serial\x18\x04 \x01(\x0b\x32\".meshtastic.SerialConnectionStatusH\x03R\x06serial\x88\x01\x01\x42\x07\n\x05_wifiB\x0b\n\t_ethernetB\x0c\n\n_bluetoothB\t\n\x07_serial\"{\n\x14WifiConnectionStatus\x12;\n\x06status\x18\x01 \x01(\x0b\x32#.meshtastic.NetworkConnectionStatusR\x06status\x12\x12\n\x04ssid\x18\x02 \x01(\tR\x04ssid\x12\x12\n\x04rssi\x18\x03 \x01(\x05R\x04rssi\"W\n\x18\x45thernetConnectionStatus\x12;\n\x06status\x18\x01 \x01(\x0b\x32#.meshtastic.NetworkConnectionStatusR\x06status\"\xb7\x01\n\x17NetworkConnectionStatus\x12\x1d\n\nip_address\x18\x01 \x01(\x07R\tipAddress\x12!\n\x0cis_connected\x18\x02 \x01(\x08R\x0bisConnected\x12*\n\x11is_mqtt_connected\x18\x03 \x01(\x08R\x0fisMqttConnected\x12.\n\x13is_syslog_connected\x18\x04 \x01(\x08R\x11isSyslogConnected\"d\n\x19\x42luetoothConnectionStatus\x12\x10\n\x03pin\x18\x01 \x01(\rR\x03pin\x12\x12\n\x04rssi\x18\x02 \x01(\x05R\x04rssi\x12!\n\x0cis_connected\x18\x03 \x01(\x08R\x0bisConnected\"O\n\x16SerialConnectionStatus\x12\x12\n\x04\x62\x61ud\x18\x01 \x01(\rR\x04\x62\x61ud\x12!\n\x0cis_connected\x18\x02 \x01(\x08R\x0bisConnectedBf\n\x14org.meshtastic.protoB\x10\x43onnStatusProtosZ\"github.com/meshtastic/go/generated\xaa\x02\x14Meshtastic.Protobufs\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meshtastic.connection_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024org.meshtastic.protoB\020ConnStatusProtosZ\"github.com/meshtastic/go/generated\252\002\024Meshtastic.Protobufs\272\002\000'
  _globals['_DEVICECONNECTIONSTATUS']._serialized_start=51
  _globals['_DEVICECONNECTIONSTATUS']._serialized_end=391
  _globals['_WIFICONNECTIONSTATUS']._serialized_start=393
  _globals['_WIFICONNECTIONSTATUS']._serialized_end=516
  _globals['_ETHERNETCONNECTIONSTATUS']._serialized_start=518
  _globals['_ETHERNETCONNECTIONSTATUS']._serialized_end=605
  _globals['_NETWORKCONNECTIONSTATUS']._serialized_start=608
  _globals['_NETWORKCONNECTIONSTATUS']._serialized_end=791
  _globals['_BLUETOOTHCONNECTIONSTATUS']._serialized_start=793
  _globals['_BLUETOOTHCONNECTIONSTATUS']._serialized_end=893
  _globals['_SERIALCONNECTIONSTATUS']._serialized_start=895
  _globals['_SERIALCONNECTIONSTATUS']._serialized_end=974
# @@protoc_insertion_point(module_scope)
