# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: meshtastic/mqtt.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'meshtastic/mqtt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from meshtastic import config_pb2 as meshtastic_dot_config__pb2
from meshtastic import mesh_pb2 as meshtastic_dot_mesh__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15meshtastic/mqtt.proto\x12\nmeshtastic\x1a\x17meshtastic/config.proto\x1a\x15meshtastic/mesh.proto\"\x7f\n\x0fServiceEnvelope\x12.\n\x06packet\x18\x01 \x01(\x0b\x32\x16.meshtastic.MeshPacketR\x06packet\x12\x1d\n\nchannel_id\x18\x02 \x01(\tR\tchannelId\x12\x1d\n\ngateway_id\x18\x03 \x01(\tR\tgatewayId\"\x9d\x05\n\tMapReport\x12\x1b\n\tlong_name\x18\x01 \x01(\tR\x08longName\x12\x1d\n\nshort_name\x18\x02 \x01(\tR\tshortName\x12\x38\n\x04role\x18\x03 \x01(\x0e\x32$.meshtastic.Config.DeviceConfig.RoleR\x04role\x12\x34\n\x08hw_model\x18\x04 \x01(\x0e\x32\x19.meshtastic.HardwareModelR\x07hwModel\x12)\n\x10\x66irmware_version\x18\x05 \x01(\tR\x0f\x66irmwareVersion\x12@\n\x06region\x18\x06 \x01(\x0e\x32(.meshtastic.Config.LoRaConfig.RegionCodeR\x06region\x12L\n\x0cmodem_preset\x18\x07 \x01(\x0e\x32).meshtastic.Config.LoRaConfig.ModemPresetR\x0bmodemPreset\x12.\n\x13has_default_channel\x18\x08 \x01(\x08R\x11hasDefaultChannel\x12\x1d\n\nlatitude_i\x18\t \x01(\x0fR\tlatitudeI\x12\x1f\n\x0blongitude_i\x18\n \x01(\x0fR\nlongitudeI\x12\x1a\n\x08\x61ltitude\x18\x0b \x01(\x05R\x08\x61ltitude\x12-\n\x12position_precision\x18\x0c \x01(\rR\x11positionPrecision\x12\x33\n\x16num_online_local_nodes\x18\r \x01(\rR\x13numOnlineLocalNodes\x12\x39\n\x19has_opted_report_location\x18\x0e \x01(\x08R\x16hasOptedReportLocationB`\n\x14org.meshtastic.protoB\nMQTTProtosZ\"github.com/meshtastic/go/generated\xaa\x02\x14Meshtastic.Protobufs\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meshtastic.mqtt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024org.meshtastic.protoB\nMQTTProtosZ\"github.com/meshtastic/go/generated\252\002\024Meshtastic.Protobufs\272\002\000'
  _globals['_SERVICEENVELOPE']._serialized_start=85
  _globals['_SERVICEENVELOPE']._serialized_end=212
  _globals['_MAPREPORT']._serialized_start=215
  _globals['_MAPREPORT']._serialized_end=884
# @@protoc_insertion_point(module_scope)
